// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdswlgensmlysfifkfdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkc3dsZ2Vuc21seXNmaWZrZmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzMzNzIsImV4cCI6MjA3MDE0OTM3Mn0.FBENC-18D7qPE92hqHQE955ZICHAVU9DbWl4mlrUj5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});